server:
  port: 8084

spring:
  application:
    name: java_ai

  datasource:
    url: jdbc:postgresql://localhost:5432/java_ai
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true